# Generated by Django 5.2.4 on 2025-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('cabelo', 'Cabelo'), ('unhas', 'Unhas'), ('barba', 'Barba'), ('maquiagem', 'Maquiagem'), ('pele', 'Pele')], max_length=20),
        ),
    ]
