# Generated by Django 5.2.4 on 2025-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, help_text="Client's date of birth", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="Client's gender", max_length=1, null=True),
        ),
    ]
