# Generated by Django 5.2.4 on 2025-08-03 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_birthday_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(xxx) xxxxx-xxxx'.", regex='^\\(\\d{3}\\) \\d{5}-\\d{4}$')]),
        ),
    ]
