# Generated by Django 5.2.4 on 2025-08-03 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
