# Generated by Django 5.2.4 on 2025-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_cli_created_4ff9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['updated_at'], name='clients_cli_updated_ee37e2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['birthday'], name='clients_cli_birthda_153408_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['gender'], name='clients_cli_gender_29da56_idx'),
        ),
    ]
