# Generated by Django 5.2.4 on 2025-12-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_appointment_appoint_5be6a4_idx_and_more'),
        ('team', '0004_alter_team_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='team.team'),
        ),
    ]
